In [4]:
import pandas as pd
import pingouin as pg
import numpy as np
from itertools import product

In [115]:

factors = ['FatorA' ,'FatorB', 'FatorC']
levels_list = [['low','high'],['L','H'],['-','+','++']]
replicates = 5
total = np.prod([len(x) for x in levels_list]) * replicates
y_measures = np.random.rand(total) #([28,25,27,18,19,23,36,32,32,31,30,29,28,25,22,18,19,23,12,32,40,31,30,29])

In [116]:
def generate_dataframe(measures, factors, levels_list, replicates):
    
    lines = []
    for factor_combination in product(*levels_list):
        line = {}
        for idx, factor in enumerate(factors):
            line[factor] = factor_combination[idx]
        for k in range(replicates):
            lines.append(line)
    df = pd.DataFrame(lines,columns=factors)
    df['y'] = measures
    #df['trial'] = list(range(replicates)) * int(len(measures) / replicates)
    return df

In [117]:
df = generate_dataframe(y_measures, factors, levels_list, replicates)

In [118]:
df

   FatorA FatorB FatorC         y
0     low      L      -  0.887593
1     low      L      -  0.016119
2     low      L      -  0.126958
3     low      L      -  0.777162
4     low      L      -  0.045895
5     low      L      +  0.710999
6     low      L      +  0.971046
7     low      L      +  0.871683
8     low      L      +  0.710162
9     low      L      +  0.958510
10    low      L     ++  0.429813
11    low      L     ++  0.872879
12    low      L     ++  0.355958
13    low      L     ++  0.929764
14    low      L     ++  0.148778
15    low      H      -  0.940029
16    low      H      -  0.832716
17    low      H      -  0.846055
18    low      H      -  0.123923
19    low      H      -  0.596487
20    low      H      +  0.016392
21    low      H      +  0.721184
22    low      H      +  0.007738
23    low      H      +  0.084822
24    low      H      +  0.225498
25    low      H     ++  0.875125
26    low      H     ++  0.363576
27    low      H     ++  0.539960
28    low      H     ++  0.568103
29    low      H     ++  0.225463
30   high      L      -  0.572147
31   high      L      -  0.660952
32   high      L      -  0.298245
33   high      L      -  0.418627
34   high      L      -  0.453089
35   high      L      +  0.932351
36   high      L      +  0.587494
37   high      L      +  0.948252
38   high      L      +  0.556035
39   high      L      +  0.500561
40   high      L     ++  0.003532
41   high      L     ++  0.480889
42   high      L     ++  0.927455
43   high      L     ++  0.198366
44   high      L     ++  0.052091
45   high      H      -  0.406779
46   high      H      -  0.372396
47   high      H      -  0.857153
48   high      H      -  0.026611
49   high      H      -  0.920149
50   high      H      +  0.680903
51   high      H      +  0.904226
52   high      H      +  0.607529
53   high      H      +  0.811953
54   high      H      +  0.335544
55   high      H     ++  0.349566
56   high      H     ++  0.389874
57   high      H     ++  0.754797
58   high      H     ++  0.369291
59   high      H     ++  0.242220

In [119]:
df.anova(dv='y', between=factors, ss_type=3).round(3)

                     Source     SS    DF     MS      F  p-unc    np2
0                    FatorA  0.000   1.0  0.000  0.005  0.943  0.000
1                    FatorB  0.033   1.0  0.033  0.394  0.533  0.008
2                    FatorC  0.241   2.0  0.121  1.439  0.247  0.057
3           FatorA * FatorB  0.087   1.0  0.087  1.039  0.313  0.021
4           FatorA * FatorC  0.246   2.0  0.123  1.470  0.240  0.058
5           FatorB * FatorC  0.671   2.0  0.336  4.004  0.025  0.143
6  FatorA * FatorB * FatorC  0.461   2.0  0.231  2.753  0.074  0.103
7                  Residual  4.023  48.0  0.084    NaN    NaN    NaN

In [84]:
data = pg.read_dataset('anova3')
data.anova(dv='Cholesterol', between=['Sex', 'Risk', 'Drug'], ss_type=3).round(3)

              Source      SS    DF      MS       F  p-unc    np2
0                Sex   2.075   1.0   2.075   2.462  0.123  0.049
1               Risk  11.332   1.0  11.332  13.449  0.001  0.219
2               Drug   0.816   2.0   0.408   0.484  0.619  0.020
3         Sex * Risk   0.117   1.0   0.117   0.139  0.711  0.003
4         Sex * Drug   2.564   2.0   1.282   1.522  0.229  0.060
5        Risk * Drug   2.438   2.0   1.219   1.446  0.245  0.057
6  Sex * Risk * Drug   1.844   2.0   0.922   1.094  0.343  0.044
7           Residual  40.445  48.0   0.843     NaN    NaN    NaN

   Sex  Risk Drug  Cholesterol
0    M   Low    A     4.868845
1    M   Low    A     6.862204
2    M   Low    A     4.602797
3    M   Low    A     3.576900
4    M   Low    A     5.739727
5    M   Low    B     5.573970
6    M   Low    B     4.862483
7    M   Low    B     4.094037
8    M   Low    B     5.011131
9    M   Low    B     4.666483
10   M   Low    C     6.507308
11   M   Low    C     5.385242
12   M   Low    C     6.614098
13   M   Low    C     4.967538
14   M   Low    C     4.487477
15   M  High    A     7.787113
16   M  High    A     5.864441
17   M  High    A     6.850206
18   M  High    A     5.432648
19   M  High    A     5.881035
20   M  High    B     6.877862
21   M  High    B     5.364989
22   M  High    B     4.615432
23   M  High    B     5.336528
24   M  High    B     6.079401
25   M  High    C     5.320824
26   M  High    C     6.342055
27   M  High    C     5.722112
28   M  High    C     6.412265
29   M  High    C     8.298304
30   F   Low    A     4.675374
31   F   Low    A     4.734142
32   F   Low    A     4.879549
33   F   Low    A     3.838024
34   F   Low    A     5.126147
35   F   Low    B     6.942870
36   F   Low    B     4.964783
37   F   Low    B     5.201249
38   F   Low    B     4.712739
39   F   Low    B     5.978741
40   F   Low    C     4.659411
41   F   Low    C     3.674954
42   F   Low    C     5.424214
43   F   Low    C     5.448216
44   F   Low    C     3.308691
45   F  High    A     5.429768
46   F  High    A     6.512341
47   F  High    A     6.199740
48   F  High    A     5.174347
49   F  High    A     5.136076
50   F  High    B     4.702679
51   F  High    B     5.599957
52   F  High    B     4.943563
53   F  High    B     5.021687
54   F  High    B     6.460949
55   F  High    C     5.151045
56   F  High    C     7.505970
57   F  High    C     7.218866
58   F  High    C     5.346000
59   F  High    C     4.876569